#' Filtering for Microbial Features of Low Abundance and Low Prevalence.
#'
#' @description
#' This function filteres an OTU/ASV table based on overal counts and prevalence thresholds, and
#'     optionally applies a logarithmic transformation. When grouping variables are provided,
#'     the function performs abundance and prevalence filtering within each group separately.
#'
#' @details
#' The function executes several key steps:
#' \enumerate{
#'   \item \strong{Input Validation:}
#'         It first checks whether the input `Data` is a data frame or a list generated by function \code{\link[MicrobTiSDA]{Data.rf.classifier}}.
#'         If `Data` is a list but not a data frame, the first element is extracted. Otherwise, if `Data` is neither a data frame nor an appropriate
#'         list, the function stops with an error.
#'
#'   \item \strong{OTU Count Filtering:}
#'         If an `OTU_counts_filter_value` is provided (i.e., not `NA`), OTUs with total counts (across all samples) less than or equal to this value are removed.
#'
#'   \item \strong{Logarithmic Transformation:}
#'         If a `log_base` is specified (allowed values are 10, 2, or e), a log transformation (with an offset of 1 to avoid log(0)) is applied to the data.
#'         If `log_base` is `NA`, the data remains untransformed.
#'
#'   \item \strong{Prevalence Filtering without Grouping:}
#'         When `Group_var` is not provided (`NULL`), if an `OTU_filter_value` is specified, the function filters out OTUs whose prevalence (the proportion of samples
#'         with a non-zero count) is less than the threshold. If `OTU_filter_value` is not provided, a warning is issued and no prevalence filtering is applied.
#'
#'   \item \strong{Group-based Prevalence Filtering:}
#'         If one or more grouping variables are specified in `Group_var`, the function first checks that these variables exist in `metadata`.
#'         For each group (or combination of groups if multiple variables are provided), the prevalence of each OTU is calculated, and OTUs are retained if they
#'         meet the prevalence threshold in at least one group. The filtered OTU table is then returned.
#' }
#'
#'
#' @param Data A data frame or a list object which contains the selected biomarker count table
#'     (generated by \code{\link[MicrobTiSDA]{Data.rf.classifier}}), where rows represent OTUs/ASVs
#'     and columns represent samples.
#' @param metadata A data frame. Containing information about all samples, including at least the grouping of all samples as well as
#'     individual information (\code{Group} and \code{ID}), the sampling \code{Time} point for each sample, and other relevant information.
#' @param OTU_counts_filter_value An integer, indicating the sum of the minimum abundances of OTUs/ASVs in all samples. If the sum
#'     of the abundances that OTU is below the given positive integer threshold, the OTU is excluded, and vice versa, it is retained.
#'     The default is 1000. Note: if the input \code{Data} is the important OTU table that produced via sample classification,
#'     this argument should be \code{NA}, As the low abundance OTUs/ASVs might be filtered out during the classification progress by
#'     \code{\link[MicrobTiSDA]{Data.rf.classifier}}.
#' @param OTU_filter_value Numeric between 0 and 1. This specifies the minimum prevalence rate of an OTU/ASV across all samples within
#'     each group or individual. OTUs/ASVs with a prevalence rate below the given threshold will be removed.
#' @param log_base This argument species the base of the logarithm. When the dataset is not very large, the default is \code{NA},
#'     and no logarithmic transformation is applied. For large datasets, the logarithm base can be 2, "e", or 10.
#' @param Group_var A string or a vector. This specifies the grouping variables, which should match the column names in
#'     the \code{metadata} used to designate sample groups, and for pre-processing OTU data of each group or individual separately.
#'     For instance, to split the OTU table based on the \code{"Group"} variable, set \code{Group_var = "Group"};
#'     to split the data based on the \code{"Group"} and \code{"Diet"} (if in \code{metadata})categorical variables to study the
#'     interaction between different grouping variables, set \code{Group_var = c("Group","Diet")}.
#'
#' @return A filtered OTU table (data frame or matrix) that has been optionally log-transformed and filtered based on the
#'     provided count and prevalence thresholds.
#' @export
#'
#' @author Shijia Li
#'
#' @examples
#' \dontrun{
#' # Create example OTU count data (rows: OTUs, columns: samples)
#' set.seed(123)
#' otu_data <- matrix(sample(1:100, 100, replace = TRUE), nrow = 10)
#' rownames(otu_data) <- paste0("OTU", 1:10)
#' colnames(otu_data) <- paste0("Sample", 1:10)
#'
#' # Create example metadata with sample grouping
#' metadata <- data.frame(Group = rep(c("A", "B"), each = 5),
#'                        row.names = paste0("Sample", 1:10))
#'
#' # Filter OTU data with group-based prevalence filtering
#' filtered2 <- Data.filter(Data = otu_data, metadata = metadata,
#'                          OTU_counts_filter_value = 200,
#'                          OTU_filter_value = 0.5,
#'                          log_base = 10,
#'                          Group_var = "Group")
#' }
#'
Data.filter <- function(Data,
                        metadata,
                        OTU_counts_filter_value = 1000,
                        OTU_filter_value = NA,
                        log_base = NA,
                        Group_var = NULL) {
  # check the type of input Data
  if (is.list(Data) == TRUE && is.data.frame(Data) != TRUE) {
    Data = Data[[1]]
  } else if (is.list(Data) == TRUE && is.data.frame(Data) == TRUE) {
    Data = Data
  } else {
    stop("The input 'Data' should either be a dataframe or the output of the function 'OTU_classifier'.")
  }

  # Check whether the input of OTU_filter_value is in [0,1]
  if (!is.na(OTU_filter_value) && (OTU_filter_value < 0 || OTU_filter_value > 1)) {
    stop("The 'OTU_filter_value' should be between 0 and 1.")
  }

  # Filtered out OTUs according to the input OTU_counts_filter_value
  if (!is.na(OTU_counts_filter_value)) {
    Data <- Data[rowSums(Data) > OTU_counts_filter_value, ]
  }

  # Conduct log-transformation
  if (!is.na(log_base)) {
    log_table <- switch(log_base,
                        `10` = apply(Data, 2, function(x) log10(x + 1)),
                        `2` = apply(Data, 2, function(x) log2(x + 1)),
                        `e` = apply(Data, 2, function(x) log(x + 1)),
                        stop("The log_base should only be 10, 2, or e"))
  } else {
    log_table <- Data
  }

  # If no 'Group_var' specified, perform low-prevalence filtering for all samples
  if (is.null(Group_var)) {
    if (is.na(OTU_filter_value)) {
      warning("No OTU_filter_value specified, returning unfiltered data.")
      log_table_filtered <- log_table
    } else {
      log_table_filtered <- log_table[rowMeans(log_table > 0) >= OTU_filter_value, ]
    }
  } else {
    # Check 'Group_var' is in metadata
    if (!all(Group_var %in% colnames(metadata))) {
      stop("Some grouping variables in 'Group_var' do not exist in 'metadata'.")
    }

    # If only one grouping variable was input
    if (length(Group_var) == 1) {
      groups <- unique(metadata[[Group_var]])
      group_OTU <- lapply(groups, function(group) {
        samples_in_group <- rownames(subset(metadata, metadata[[Group_var]] == group))
        log_table[, samples_in_group]
      })
    } else {
      # If multiple grouping variables were input
      metadata$Group_combo <- interaction(metadata[, Group_var, drop = FALSE])
      groups <- unique(metadata$Group_combo)
      group_OTU <- lapply(groups, function(group) {
        samples_in_group <- rownames(subset(metadata, metadata$Group_combo == group))
        log_table[, samples_in_group]
      })
    }

    # Calculate OTUs prevalences in each group, and filter out OTUs with prevalences lower than the threshold.
    OTU_frequencies <- lapply(group_OTU, function(group) rowMeans(group > 0))
    selected_OTU <- lapply(OTU_frequencies, function(frequencies) {
      names(frequencies[frequencies >= OTU_filter_value])
    })

    # combine retained OTUs
    common_OTU <- unique(unlist(selected_OTU))
    log_table_filtered <- log_table[common_OTU, , drop = FALSE]
  }

  return(log_table_filtered)
}
