#' @title Cut and Annotate Dendrogram Based on a Specified Cut-Off Height
#' @description
#' This function processes clustering outputs from \code{\link[MicrobTiSDA]{Data.cluster}} to update dendrogram plots.
#'     Depending on the user’s preference, it either automatically determines the optimal number of clusters via
#'     silhouette analysis or uses a user-specified cut-off height.
#'
#' @details
#' The function takes as input a list containing predicted data and clustering results (typically generated by another function) from
#'     \code{\link[MicrobTiSDA]{Data.cluster}}, and then computes a correlation-based distance matrix for each group. If \code{auto_cutree}
#'     is \code{TRUE}, the function performs a repeated k-fold cross-validation by iterating over a range of potential cluster numbers
#'     and computing the average silhouette width, thereby determining the optimal number of clusters. The dendrogram is then cut accordingly,
#'     and the resulting clusters are used to annotate the dendrogram plot with different colors for each cluster.
#'
#' If \code{auto_cutree} is \code{FALSE}, the function uses the provided \code{cut_height} to cut the dendrogram. It then assigns cluster
#'     emberships based on this cut-off and updates the dendrogram plot by adding a horizontal dashed line at the specified cut-off and annotating
#'     the plot with the cut-off value. In both cases, the function prints the dendrogram plot for each group and returns a list containing the
#'     clustering results and the corresponding ggplot2 objects of the dendrograms.
#'
#'
#' @param cluster_outputs The output object of \code{\link[MicrobTiSDA]{Data.cluster}}.
#' @param cut_height A numeric value specifying the cut-off height for cutting the dendrogram when \code{auto_cutree} is \code{FALSE}.
#' @param cut_height_dist A numeric value used to adjust the vertical distance of the cut-off line annotation in the dendrogram
#'     plot (default: \code{0.2}).
#' @param auto_cutree Logical; if \code{TRUE}, the function automatically determines the optimal number of clusters based on
#'     silhouette width (default: \code{FALSE}).
#' @param font_size A numeric value specifying the font size for text labels in the dendrogram plots (default: \code{0.2}).
#'
#' @return A list with two elements:
#' \describe{
#'   \item{cluster_results}{A list of clustering objects for each group.}
#'   \item{cluster_figures}{A list of ggplot2 objects containing the annotated dendrogram plots for each group.}
#' }
#'
#' @importFrom stats as.dist cor hclust as.dendrogram cutree
#' @importFrom cluster silhouette
#' @import ggplot2
#' @import ggdendro
#' @importFrom utils read.table
#' @export
#' @author Shijia Li
#'
#' @examples
#' \dontrun{
#' # Suppose you have clustering outputs from a previous analysis stored in 'clust_out'
#' # To use a user-specified cut-off height:
#' result <- Data.cluster.cut(cluster_outputs = clust_out, cut_height = 0.3, cut_height_dist = 0.2, auto_cutree = FALSE)
#'
#' # To automatically determine the optimal number of clusters:
#' result_auto <- Data.cluster.cut(cluster_outputs = clust_out, auto_cutree = TRUE)
#' }
Data.cluster.cut = function(cluster_outputs,
                            cut_height,
                            cut_height_dist = 0.2,
                            font_size = 0.2,
                            auto_cutree = FALSE) {

  cluster_results = cluster_outputs[[2]]
  predict_data = cluster_outputs[[1]]
  cluster_figures = list()

  for (i in names(predict_data)) {

    pred_data = as.data.frame(predict_data[[i]][, -ncol(predict_data[[i]])])
    cor_matrix = cor(pred_data)
    pred_data_dist = as.dist((1 - cor_matrix))

    if (auto_cutree == TRUE) {
      max_k = ncol(pred_data) - 1
      sil_width = numeric(max_k)
      for (k in 2:max_k) {
        cutree_k = cutree(cluster_results[[i]], k)
        sil = cluster::silhouette(cutree_k, pred_data_dist)
        sil_width[k] = mean(sil[, 3])
      }
      optimal_k = which.max(sil_width)
      cat("Number of optimal clusters for group", i, ":", optimal_k, "\n")
      dend = as.dendrogram(cluster_results[[i]])
      clusters = cutree(cluster_results[[i]], optimal_k)[order.dendrogram(dend)]
      clusters.df = data.frame(label = names(clusters), cluster = factor(clusters))
      dend_data = ggdendro::dendro_data(dend, type = "rectangle")
      dend_data[["labels"]] <- merge(dend_data[["labels"]], clusters.df, by = "label")

      cluster_figures[[i]] = ggplot() +
        geom_segment(data = dend_data$segments, aes(x = x, y = y, xend = xend, yend = yend)) +
        geom_text(data = dend_data$labels, aes(x = x, y = y, label = label, color = cluster),
                  size = font_size, hjust = 0) +
        coord_flip() + scale_y_reverse(expand = c(0.2, 0)) +
        labs(title = paste("OTU profiles clustering plot for group", i, "\nSuggested optimal cluster:", optimal_k)) +
        theme(axis.line.y = element_blank(),
              axis.ticks.y = element_blank(),
              axis.title.x = element_blank(),
              axis.text.y = element_blank(),
              axis.title.y = element_blank(),
              panel.background = element_rect(fill = "white"),
              panel.grid = element_blank()) +
        scale_color_discrete(name = "Cluster")
      print(cluster_figures[[i]])
    } else {
      dend = as.dendrogram(cluster_results[[i]])
      cut_height = as.numeric(cut_height)

      clusters = cutree(cluster_results[[i]], h = cut_height)
      clusters_ordered = clusters[order.dendrogram(dend)]
      clusters_df = data.frame(label = names(clusters_ordered), cluster = factor(clusters_ordered))

      dend_data = ggdendro::dendro_data(dend, type = "rectangle")
      dend_data[["labels"]] <- merge(dend_data[["labels"]], clusters_df, by = "label", all.x = TRUE)

      cluster_figures[[i]] =  ggplot() +
        geom_segment(data = dend_data$segments, aes(x = x, y = y, xend = xend, yend = yend)) +
        geom_text(data = dend_data$labels, aes(x = x, y = y, label = label, color = cluster),
                  size = font_size, hjust = 0) +
        coord_flip() + scale_y_reverse(expand = c(0.2, 0)) +
        labs(title = paste("OTU profiles clustering plot for group", i)) +
        theme(axis.line.y = element_blank(),
              axis.ticks.y = element_blank(),
              axis.title.x = element_blank(),
              axis.text.y = element_blank(),
              axis.title.y = element_blank(),
              panel.background = element_rect(fill = "white"),
              panel.grid = element_blank()) +
        scale_color_discrete(name = "Cluster") +
        geom_hline(yintercept = cut_height, color = "blue", linetype = "dashed") +
        annotate("text", x = 3, y = cut_height + cut_height_dist,
                 label = paste("Cut-off line:", cut_height), color = "blue")

      print(cluster_figures[[i]])
    }
  }
  cluster_data = list(cluster_results, cluster_figures)
  names(cluster_data) = c("cluster_results", "cluster_figures")
  return(cluster_data)
}
