#' @title Visualize Microbial Interaction Networks
#' @description
#' This function visualizes microbial species interactions based on the given inter-species interaction results by \code{\link[MicrobTiSDA]{Spec.interact}}.
#'
#' @param Interact_data A list containing the inferred species interaction results generated by \code{\link[MicrobTiSDA]{Spec.interact}}.
#' @param count_data A matrix or data frame of the transformed species abundance data.
#' @param metadata A data frame. Containing information about all samples, including at least the grouping of all samples as well as
#'     individual information (\code{Group} and \code{ID}), the sampling \code{Time} point for each sample, and other relevant information.
#' @param Subject_ID A character string specifying the column name in metadata that identifies subjects.
#' @param Interact_threshold A numeric value specifying the minimum absolute interaction strength to include in the network.
#' @param Taxa A data frame providing taxonomic annotations for microbial species.
#' @param label_font_size A numeric value specifying the font size for species labels in the network (default: 3).
#' @param label_distance A numeric value controlling the distance of labels from nodes (default: 0.15).
#' @param title_size A numeric value specifying the font size of the plot title (default: 5).
#' @param legend_title_size A numeric value specifying the font size of the legend title (default: 3).
#' @param legend_text_size A numeric value specifying the font size of the legend text (default: 3).
#'
#' @return A list of ggplot2 objects, each representing an interaction network for a subject.
#' @details
#' The function processes microbial interaction matrices from \code{\link[MicrobTiSDA]{Spec.interact}} to construct species interaction networks.
#' It selects edges with absolute interaction strengths above \code{Interact_threshold}, assigns interaction types (positive or negative), and
#' applies a circular layout for visualization. The function supports onpional taxonomic annotations for improved interpretability.
#'
#' The nodes represent microbial species, sized according to their log-median abundance across samples. Edge colors indicate interaction types:
#' blue for negative and orange for positive interactions. Edge widths are scaled by interaction strength. If taxonomic annotations are provided,
#' node labels reflect species-level taxonomy; otherwise, OTU/ASV IDs are used.
#'
#' @export
#' @author Shijia Li
#' @import dplyr tidygraph ggraph
#' @importFrom ggplot2 ggplot
#' @importFrom tidyr pivot_longer
#' @importFrom stats median
#' @importFrom tibble rownames_to_column
#'
Interact.vis = function(Interact_data, count_data, metadata, Subject_ID, Interact_threshold, Taxa=NULL,
                        label_font_size = 3, label_distance = 0.15,title_size = 5,legend_title_size = 3,
                        legend_text_size = 3) {
  figure_list = list()
  count_data = as.data.frame(t(count_data))
  for (g in names(Interact_data)) {
    g_interact = as.data.frame(Interact_data[[g]][['final_interaction_matrix']])
    g_count_data = count_data[,rownames(subset(metadata, metadata[[Subject_ID]] == g))]
    g_count_data_mean = log(apply(g_count_data, 1, median) + 1)

    df = tibble::rownames_to_column(g_interact, var = 'From')
    long_table = df %>% pivot_longer(cols = -From, names_to = 'To', values_to = 'Interaction') %>%
      as.data.frame()
    long_table = subset(long_table, abs(Interaction) >= Interact_threshold)

    edges = long_table
    edges$Class = ifelse(edges$Interaction > 0, "Positive", 'Negative')

    edges = edges %>%
      dplyr::group_by(From, To) %>%
      dplyr::mutate(edge_count = dplyr::n()) %>%
      dplyr::group_by(From, To) %>%
      dplyr::mutate(curve_dir = if(edge_count > 1) {
        seq(-1, 1, length.out = edge_count)[row_number()]
      } else {
        0
      }) %>% dplyr::ungroup()

    nodes = data.frame(name = unique(union(long_table$From, long_table$To)))
    nodes$Mean_value = g_count_data_mean[rownames(g_count_data) %in% nodes$name]

    if (!is.null(Taxa)) {
      Annotate = Taxa[match(nodes$name, rownames(Taxa)), ]
      Annotate = Annotate %>%
        dplyr::mutate(across(where(is.factor), as.character)) %>%
        dplyr::mutate(across(everything(), ~na_if(., "")))
      Taxon = apply(Annotate, 1, function(x) { tail(na.omit(x), 1) })
      Taxon = data.frame(Species_annotation = Taxon)
      nodes$taxa = Taxon[, 1]

      plot_data = tidygraph::tbl_graph(nodes = nodes, edges = edges)
      n_nodes = nrow(nodes)
      radius_scale = 1 + log(n_nodes) / 20

      layout <- ggraph::create_layout(plot_data, layout = 'linear', circular = TRUE)
      layout$x = layout$x / radius_scale
      layout$y = layout$y / radius_scale

      label_data <- data.frame(
        x = layout$x,
        y = layout$y,
        name = nodes$taxa
      )

      angles <- atan2(label_data$y, label_data$x)
      radius <- sqrt(label_data$x^2 + label_data$y^2)
      #adjusted_label_distance = label_distance / sqrt(n_nodes/10)
      adjusted_label_distance = label_distance+(2/n_nodes)
      label_data$label_x <- label_data$x + cos(angles) * (radius * adjusted_label_distance)
      label_data$label_y <- label_data$y + sin(angles) * (radius * adjusted_label_distance)
      label_data$angle <- ifelse(angles > pi/2 | angles < -pi/2,
                                 (angles * 180 / pi) + 180,
                                 angles * 180 / pi)

      Interact_plot = ggraph::ggraph(plot_data, layout = 'linear', circular = TRUE) +
        ggraph::geom_node_point(alpha = 1, aes(size = Mean_value)) +
        geom_text(data = label_data,
                  aes(x = label_x, y = label_y, label = name),
                  angle = label_data$angle,
                  size = label_font_size,
                  hjust = 0.5,
                  vjust = 0.5) +
        ggraph::geom_node_point(size = 2) +
        ggraph::geom_edge_arc(aes(colour = Class,
                          width = abs(Interaction)),
                      alpha = 0.8,
                      strength = edges$curve_dir * 0.2,
                      arrow = arrow(length = unit(4, "mm"),
                                    type = "closed",
                                    angle = 20),
                      start_cap = ggraph::circle(3, "mm"),
                      end_cap = ggraph::circle(3, "mm")) +
        ggraph::scale_edge_colour_manual(values = c('blue', '#ed7d31'),
                                 name = 'Interaction types') +
        ggraph::scale_edge_width_continuous(range = c(0.3, 2),
                                    name = 'Interaction strength') +
        scale_size_continuous(name = 'Log-median abundance') +
        labs(title = paste('Species interactions of', g)) +
        ggraph::theme_graph() +
        coord_cartesian(clip = "off")+
        theme(plot.title = element_text(size = title_size),
              legend.title = element_text(size = legend_title_size),
              legend.text = element_text(size = legend_text_size))

    } else {
      plot_data = tidygraph::tbl_graph(nodes = nodes, edges = edges)
      n_nodes = nrow(nodes)
      radius_scale = 1 + log(n_nodes) / 20

      layout <- ggraph::create_layout(plot_data, layout = 'linear', circular = TRUE)
      layout$x = layout$x / radius_scale
      layout$y = layout$y / radius_scale

      label_data <- data.frame(
        x = layout$x,
        y = layout$y,
        name = nodes$name
      )

      angles <- atan2(label_data$y, label_data$x)
      radius <- sqrt(label_data$x^2 + label_data$y^2)
      #adjusted_label_distance = label_distance / sqrt(n_nodes/10)
      adjusted_label_distance = label_distance+(2/n_nodes)
      label_data$label_x <- label_data$x + cos(angles) * (radius * adjusted_label_distance)
      label_data$label_y <- label_data$y + sin(angles) * (radius * adjusted_label_distance)
      label_data$angle <- ifelse(angles > pi/2 | angles < -pi/2,
                                 (angles * 180 / pi) + 180,
                                 angles * 180 / pi)

      Interact_plot = ggraph::ggraph(plot_data, layout = 'linear', circular = TRUE) +
        ggraph::geom_node_point(alpha = 1, aes(size = Mean_value)) +
        geom_text(data = label_data,
                  aes(x = label_x, y = label_y, label = name),
                  angle = label_data$angle,
                  size = label_font_size,
                  hjust = 0.5,
                  vjust = 0.5) +
        ggraph::geom_node_point(size = 2) +
        ggraph::geom_edge_arc(aes(colour = Class,
                          width = abs(Interaction)),
                      alpha = 0.8,
                      strength = edges$curve_dir * 0.2,
                      arrow = arrow(length = unit(4, "mm"),
                                    type = "closed",
                                    angle = 20),
                      start_cap = ggraph::circle(3, "mm"),
                      end_cap = ggraph::circle(3, "mm")) +
        ggraph::scale_edge_colour_manual(values = c('blue', '#ed7d31'),
                                 name = 'Interaction types') +
        ggraph::scale_edge_width_continuous(range = c(0.3, 2),
                                    name = 'Interaction strength') +
        scale_size_continuous(name = 'Log-median abundance') +
        labs(title = paste('Species interactions of', g)) +
        ggraph::theme_graph() +
        coord_cartesian(clip = "off")+
        theme(plot.title = element_text(size = title_size),
              legend.title = element_text(size = legend_title_size),
              legend.text = element_text(size = legend_text_size))
    }
    figure_list[[g]] = Interact_plot
  }
  return(figure_list)
}
