#' @title Predict Time-Series Data from Fitted Spline Models
#' @description
#' This function generates predicted OTU abundances at new time points using previously fitted spline regression models.
#'     For each subject defined in the fitted models, it extracts the time range from the metadata, creates a new sequence of time points
#'     with a specified interval, and uses the corresponding fitted models to predict values at these new time points.
#'
#' @details
#' The function accepts a list of fitted models (typically the output from \code{\link[MicrobTiSDA]{Reg.SPLR}}) and sample metadata.
#'     For each subject (as defined by the \code{Group} parameter), it extracts the subset of metadata corresponding to that subject. The minimum and maximum time
#'     values are determined, and a new sequence of time points is generated using the provided \code{time_step}. For each OTU model of the
#'     subject, predictions are obtained via the \code{predict} function applied to the new time points, and the results are compiled into a data
#'     frame with an additional column \code{Predicted_Time} indicating the prediction time. The output is a list of data frames, each corresponding
#'     to a subject, containing the predicted OTU abundances.
#'
#' @param Fitted_models A list object generated by \code{\link[MicrobTiSDA]{Reg.SPLR}}.
#' @param metadata A data frame. Containing information about all samples, including at least the grouping of all samples as well as
#'     individual information (\code{Group} and \code{ID}), the sampling \code{Time} point for each sample, and other relevant information.
#' @param Group A character string indicating the column name in \code{metadata} that defines subject information for prediction.
#' @param time_step A numeric value specifying the interval between new time points in the prediction sequence.
#' @param Sample_Time A character string indicating the column name in \code{metadata} that contains sample time information.
#'
#' @return A list of data frames. Each element of the list corresponds to a group and contains the predicted OTU abundances at the
#'   new time points, with rows labeled by the group and time (formatted as \code{Group_T_Time}) and an additional column \code{Predicted_Time}.
#' @export
#' @author Shijia Li
#'
#' @examples
#' \dontrun{
#' # Assuming Fitted_models is obtained from a spline regression fitting function (e.g., Reg.SPLR) and metadata is available:
#' predictions <- Pred.data(Fitted_models, metadata, Group = "Subject", time_step = 1, Sample_Time = "TimePoint")
#' # View predictions for a specific group:
#' head(predictions[["Subject1"]])
#' }
Pred.data = function(Fitted_models, metadata, Group, time_step, Sample_Time) {

  predicted_data = list()
  fitted_models = Fitted_models$fitted_model

  for (i in names(fitted_models)) {
    colnames(metadata)[colnames(metadata) == Sample_Time] = 'Time'
    meta_group = metadata[rownames(metadata[metadata[Group] == i,]),]
    start_time = min(meta_group['Time'])
    end_time = max(meta_group['Time'])
    New_time = seq(start_time,end_time,time_step)

    pred_data = as.data.frame(matrix(0,length(New_time),
                                     length(fitted_models[[i]])))
    rownames(pred_data) = paste(i,"_T_",New_time,sep = "")
    colnames(pred_data) = names(fitted_models[[i]])

    for (j in 1:length(fitted_models[[i]])) {
      pred_data[,j] = predict(fitted_models[[i]][[j]],
                              data.frame(Time = New_time))
    }

    pred_data = as.data.frame(pred_data) %>%
      mutate(.,Predicted_Time = New_time)

    predicted_data[[i]] = pred_data
  }

  return(predicted_data)
}
